name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm check

      - name: Test
        run: pnpm test

      - id: 'auth'
        name: Setup Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'my-sandbox-385103'
          service_account: 'cloud-run-workload-identity@my-sandbox-385103.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/605980776054/locations/global/workloadIdentityPools/demo-workload-identity-pool/providers/github'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 471.0.0'
          
      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build
        run: |
          docker build -t ${{ secrets.GCLOUD_ARTIFACT_REGISTRY }}/demo-app:latest ./

      - name: Push
        run: |
          docker push ${{ secrets.GCLOUD_ARTIFACT_REGISTRY }}/demo-app
